import { NextPage } from "next";
import Head from "next/head";

import { Index as Header } from "@/components/ctas";
import { Index as About } from "@/components/about";
import { Index as Services } from "@/components/services";
import { Index as Testimonials } from "@/components/testimonials";
import { Index as Pricing } from "@/components/pricing";
import { Index as Contact } from "@/components/contact";
import { Index as Footer } from "@/components/footer.tsx";

import Divider from "@/elements/layout/divider";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>wind-fit</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <Header />
      <About />
      <Pricing />
      <Services />
      <Testimonials />
      <Divider />
      <Contact />

      <Footer />
    </>
  );
};

export default Index;
